# Hardcoded Comms Audit Data from 250915_SKO_Ads Overview.xlsx
# This data is automatically loaded by the app

comms_audit_data = [
    {
        'Medium': 'Video',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1998.22,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1741.78,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1686.67,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 252.86,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 204.11,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 201.33,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 231.13,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 229.81,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 225.39,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 219.86,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 216.56,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 206.44,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 200.37,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 252.55,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 206.72,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 206.35,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 201.97,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 201.79,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 200.7,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Pinterest',
        'Market': 'ES',
        'Outcome': 'Brand',
        'Spend': 199.75,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 24861.6448005,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 16742.9858895,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 10463.561661,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 9320.9250555,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 8255.18436,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 6854.993401,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 6656.00997675,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Brand',
        'Spend': 6346.29503375,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 5916.01124725,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 5614.58679125,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 4153.777671599999,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 2855.511835199999,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 2820.4536312,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 2651.0572704,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': True,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Brand',
        'Spend': 2053.6833084,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 1718.2532646,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 1689.915723,
        'Electric Green': False,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 1638.9991962,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 1557.2788512,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 1499.7660318,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 39827.21,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 38002.42,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 36588.92,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 34993.17,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 33259.7,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 30407.38,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 27968.78,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 27679.0,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 27148.71,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 26594.7,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Promotion',
        'Spend': 33461.53469119999,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': True,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 31415.7064536,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 23856.84308,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Promotion',
        'Spend': 22497.0940656,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 18272.4943016,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Brand',
        'Spend': 18200.0672896,
        'Electric Green': False,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Promotion',
        'Spend': 18199.4410192,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': True,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 18161.1573416,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 31865.29,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 25450.35,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 15932.66,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 13532.76,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 12072.85,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Product',
        'Spend': 10824.59,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 8541.01,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 5341.73,
        'Electric Green': True,
        'Emerald Green': False,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': True,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 4201.28,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Image',
        'Placement': 'Meta',
        'Market': 'GER',
        'Outcome': 'Promotion',
        'Spend': 3859.75,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': True,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 1250000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1050000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1150000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 1150000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1220000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1020000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 690000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1320000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Product',
        'Spend': 1080000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'ES',
        'Outcome': 'Promotion',
        'Spend': 760000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'UK',
        'Outcome': 'Brand',
        'Spend': 1010000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 2870000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 1440000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'UK',
        'Outcome': 'Product',
        'Spend': 1300000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 340000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': True,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 430000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 260000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': True,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Brand',
        'Spend': 270000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 330000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 280000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': True,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Brand',
        'Spend': 880000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': True,
        'Symbol': True,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 140000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'GER',
        'Outcome': 'Brand',
        'Spend': 250000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'TVC',
        'Market': 'GER',
        'Outcome': 'Product',
        'Spend': 1430000.0,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 34014.6728376,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 17608.9672122,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': False,
        'Symbol': True,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 15697.6584492,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': False,
        'Facets': False,
        'Sonic': False,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 10932.1761822,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': False,
        'Tagline': False,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 8422.709022,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 8257.353468,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 7452.8234508,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Promotion',
        'Spend': 6514.597962599999,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 6468.158478599999,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
    {
        'Medium': 'Video',
        'Placement': 'YouTube',
        'Market': 'POL',
        'Outcome': 'Product',
        'Spend': 5849.186834399999,
        'Electric Green': True,
        'Emerald Green': True,
        'Type': True,
        'Tagline': True,
        'Symbol': False,
        'Hacek': False,
        'Wordmark': True,
        'Facets': False,
        'Sonic': True,
    },
]
